// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/producer/grpc/notice.proto

package notice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type NoticeRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type                 int64    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreateTime           string   `protobuf:"bytes,4,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeRequest) Reset()         { *m = NoticeRequest{} }
func (m *NoticeRequest) String() string { return proto.CompactTextString(m) }
func (*NoticeRequest) ProtoMessage()    {}
func (*NoticeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e29b2b30567934, []int{0}
}

func (m *NoticeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeRequest.Unmarshal(m, b)
}
func (m *NoticeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeRequest.Marshal(b, m, deterministic)
}
func (m *NoticeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeRequest.Merge(m, src)
}
func (m *NoticeRequest) XXX_Size() int {
	return xxx_messageInfo_NoticeRequest.Size(m)
}
func (m *NoticeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeRequest proto.InternalMessageInfo

func (m *NoticeRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *NoticeRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NoticeRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *NoticeRequest) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

// The response message containing the greetings
type ProducerResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProducerResponse) Reset()         { *m = ProducerResponse{} }
func (m *ProducerResponse) String() string { return proto.CompactTextString(m) }
func (*ProducerResponse) ProtoMessage()    {}
func (*ProducerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0e29b2b30567934, []int{1}
}

func (m *ProducerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerResponse.Unmarshal(m, b)
}
func (m *ProducerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerResponse.Marshal(b, m, deterministic)
}
func (m *ProducerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerResponse.Merge(m, src)
}
func (m *ProducerResponse) XXX_Size() int {
	return xxx_messageInfo_ProducerResponse.Size(m)
}
func (m *ProducerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerResponse proto.InternalMessageInfo

func (m *ProducerResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ProducerResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ProducerResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*NoticeRequest)(nil), "notice.NoticeRequest")
	proto.RegisterType((*ProducerResponse)(nil), "notice.ProducerResponse")
}

func init() { proto.RegisterFile("app/producer/grpc/notice.proto", fileDescriptor_e0e29b2b30567934) }

var fileDescriptor_e0e29b2b30567934 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x8d, 0x2d, 0xc5, 0x1d, 0x14, 0x96, 0x01, 0x21, 0x78, 0x58, 0x96, 0x9e, 0xf6, 0xb4,
	0x05, 0x3d, 0x89, 0xaf, 0x20, 0x22, 0xc1, 0x17, 0x88, 0xc9, 0xb8, 0xe4, 0xb0, 0x4d, 0x4c, 0xd2,
	0x43, 0xaf, 0x3e, 0xb9, 0x64, 0xda, 0x82, 0xf5, 0xb8, 0xb7, 0x5f, 0xbe, 0x90, 0xef, 0x4f, 0x60,
	0xa7, 0x43, 0xe8, 0x42, 0xf4, 0x76, 0x30, 0x14, 0xbb, 0x53, 0x0c, 0xa6, 0xeb, 0x7d, 0x76, 0x86,
	0x8e, 0x21, 0xfa, 0xec, 0xb1, 0x99, 0x4e, 0xad, 0x83, 0xbb, 0x37, 0x26, 0x45, 0xdf, 0x03, 0xa5,
	0x8c, 0x5b, 0xa8, 0x06, 0x67, 0xa5, 0xd8, 0x8b, 0x43, 0xa5, 0x0a, 0x22, 0x42, 0x9d, 0xc7, 0x40,
	0xf2, 0x9a, 0x25, 0xe6, 0xa2, 0x59, 0x9d, 0xb5, 0xac, 0xf6, 0xe2, 0xb0, 0x51, 0xcc, 0xb8, 0x03,
	0x30, 0x91, 0x74, 0xa6, 0x0f, 0x77, 0x26, 0x59, 0xf3, 0xcd, 0x1f, 0xa5, 0x7d, 0x85, 0xed, 0xfb,
	0x5c, 0x48, 0x51, 0x0a, 0xbe, 0x4f, 0xec, 0x63, 0xbc, 0xa5, 0x39, 0x8e, 0xb9, 0x34, 0x38, 0xa7,
	0x13, 0xc7, 0x6d, 0x54, 0xc1, 0x55, 0xda, 0xed, 0x94, 0xf6, 0xf8, 0x23, 0xe0, 0x66, 0xb1, 0xc3,
	0x17, 0x68, 0xca, 0x8a, 0xaf, 0x11, 0xef, 0x8f, 0xf3, 0xcc, 0xd5, 0xaa, 0x07, 0xb9, 0xc8, 0xff,
	0x1b, 0xb4, 0x57, 0xf8, 0x0c, 0xb5, 0x22, 0x6d, 0x2f, 0x78, 0xfa, 0xd9, 0xf0, 0x67, 0x3e, 0xfd,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x62, 0x68, 0x5d, 0x59, 0x6e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProducerClient is the client API for Producer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProducerClient interface {
	// Sends a greeting
	Notify(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*ProducerResponse, error)
	Read(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*ProducerResponse, error)
}

type producerClient struct {
	cc *grpc.ClientConn
}

func NewProducerClient(cc *grpc.ClientConn) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Notify(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*ProducerResponse, error) {
	out := new(ProducerResponse)
	err := c.cc.Invoke(ctx, "/notice.Producer/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) Read(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*ProducerResponse, error) {
	out := new(ProducerResponse)
	err := c.cc.Invoke(ctx, "/notice.Producer/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServer is the server API for Producer service.
type ProducerServer interface {
	// Sends a greeting
	Notify(context.Context, *NoticeRequest) (*ProducerResponse, error)
	Read(context.Context, *NoticeRequest) (*ProducerResponse, error)
}

// UnimplementedProducerServer can be embedded to have forward compatible implementations.
type UnimplementedProducerServer struct {
}

func (*UnimplementedProducerServer) Notify(ctx context.Context, req *NoticeRequest) (*ProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (*UnimplementedProducerServer) Read(ctx context.Context, req *NoticeRequest) (*ProducerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}

func RegisterProducerServer(s *grpc.Server, srv ProducerServer) {
	s.RegisterService(&_Producer_serviceDesc, srv)
}

func _Producer_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notice.Producer/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Notify(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notice.Producer/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Read(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Producer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notice.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _Producer_Notify_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Producer_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/producer/grpc/notice.proto",
}
